### ISSUE TITLE
I can't remove a page

### ISSUE THREAD

**Issue by LeninZapata** [maxlath/time-capsule#10]
Hello, I have a page that repeats every 3 hours, when it appears again I put it in the extension "never" but it still appears to me, what can I do to avoid this error?

**Comment by maxlath** [comment]
@LeninZapata is it possible that the bookmarked page is a redirection? in which case when the bookmark is reopened, the page is directly redirected and the "never" button tries to act on another URL than the one bookmarked. The easiest way to solve this kind of issue is to open the bookmark manager (Ctrl+Shift+H on Firefox, Ctrl+Shift+O on Chrome), go in the "Time Capsule" folder, filter with the bookmark domain to find the desired bookmark, and delete it

**Comment by LeninZapata** [comment]
Ok it works

**Comment by waldyrious** [comment]
This should probably be placed in a FAQ somewhere. Maybe a wiki page in this repository?
