### ISSUE TITLE
Allow one-off snoozes (not just recurring events)

### ISSUE THREAD

**Issue by caponica** [maxlath/time-capsule#12]
This project is great, and I love the time travel references.

The one thing I cannot do at the moment, and I really want to do, is to be able to send a single "package" to my future self at a particular moment in time. E.g. I have a tab with a picture of a Tribble. I want to send that to the future me that lives 15 mins in the future, so he can examine the Tribble then.

All my future selves do not need Tribbles... we all know what they're like and we don't want to encourage them. I don't need to send it to every future self 15 mins apart and face Star Fleet court martial for the consequences. Especially if I'm AFK for a few hours.

Just a one-off trip to the future for a single Tribble tab would be fine, and my future self can decide what to do with it when it arrives.

Maybe an extra row of options on the pop-up saying:
**Snooze once:**
15m 1h 3h 1d X

Where X is a custom length.
And in the secret typing box on the popup being able to type "s15t" for "Snooze for 15 minutes"  (or s-numbers-interval for any interval) would be great too.

Thank you!

**Comment by waldyrious** [comment]
I was going to suggest the same. I get the sense that this extension is trying to focus on recurring/cyclic browsing needs rather than one-off snoozes, but IMO there's sufficient overlap in the needs of both use cases to justify that the feature be considered.

In fact, I'd even go as far as to suggest making the one-off snooze the default operation, and the recurring functionality as an option, as similar to a calendar event that can be set to a recurring schedule.

**Comment by jum-s** [comment]
A slightly different use case in the way of setting the future snooze:
I got news that this event happens on 15th of December at 18h00, i would like to send a tab about this event to my future self at a precise time and date (ie. having a date and time picker of some kind).
If the browser is off at that time, open the tab only once next time it is on.

**Comment by maxlath** [comment]
I was finally able to publish a new version (`v2.3.3`), which includes 2 new capsule creation modes: one-time capsules, and advanced mode. It should hopefully cover your different Tribble-related needs, let me know if that does the job!

Closing this issue for now, but feel welcome to re-open if that's not giving you full satisfaction. In case of incident brought to the attention of the Star Fleet court martial, beware that I will deny any responsibility though, in accordance with the AGPL "Limitation of Liability" clause ;)

**Comment by waldyrious** [comment]
Woohoo! I just noticed this change. I particularly like the advanced mode (I may or may not have manually edited my bookmarks so the capsules emerge at a neat round time :grin:). Thanks for implementing this! :bow:
