### ISSUE TITLE
Prevent Time Capsule from opening during certain time

### ISSUE THREAD

**Issue by kunsip** [maxlath/time-capsule#16]
This is useful if you're a person who works from home and uses the same computer for work and play. 

I can design  the time management engine. 

Idea:

Block Time Capsule Wormhole from occuring between 07:30 - 18:30
  If link was to open during block, put on hold until after blocked time.
  Only open pending links ONCE in non blocking time. 

if(wormhole.isBlocked()){
    wormhole.addToPendingOpen(link)
}

//Detection code
// Changing times will automatically flush the wormhole if the wormhole is no longer blocked
// To conserve power, only check wormhole opening upon browser launch and if not time (set a callback to call 1 minute after the blocked time)

**Comment by maxlath** [comment]
It took a while due to time travel paradoxes, but this has been implemented in c13bb39 dc9f84d 6f4e3b3 0095e24, and now published in `v2.3.3`
