### ISSUE TITLE
Link to snooze tabs extension doesn't work for me

### ISSUE THREAD

**Issue by waldyrious** [maxlath/time-capsule#19]
The link to in https://testpilot.firefox.com/experiments/snooze-tabs in https://github.com/maxlath/time-capsule/blob/a58aeff06b160c680b711c6283c370ed8fca6d2d/marketplaces/mozilla/description.html#L30 doesn't work for me. In fact, any links to https://testpilot.firefox.com (including this direct link to the top-level of the subdomain) redirect to https://fpn.firefox.com, where I see a message "This extension is currently only available in the United States."

I would recommend changing that link to https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/.

**Comment by maxlath** [comment]
fixed in 6586f2c
