### ISSUE TITLE
Please add the addon icon in the bookmarks bar for dark themes.

### ISSUE THREAD

**Issue by vitalii2011** [maxlath/time-capsule#22]
Now, with Beautiful Opera Dark https://addons.mozilla.org/en/firefox/addon/beautiful-opera-dark/ :
![Image 001](https://user-images.githubusercontent.com/41552153/208869468-d3401998-dca7-4ae9-b118-906016187bfd.png)
And for Website History Browser at the same time :)
![Image 002](https://user-images.githubusercontent.com/41552153/208869788-a1d421ea-9ad1-41fc-9c83-be4a4cb56c6f.png)

**Comment by maxlath** [comment]
Done for both extensions :D

Time Capsule v2.3.3
Website History Browser v1.3.0
