### ISSUE TITLE
Avoid duplicating tabs

### ISSUE THREAD

**Issue by olliebean** [maxlath/time-capsule#7]
As it is now, a URL will open at the prescribed periodicity whether or not there is already a tab open to that URL. So if I am away from my computer for several periods, I will return to find several duplicate tabs open. Would it be possible to open the URL only if it isn't already open in an existing tab?

**Comment by maxlath** [comment]
the problem is that some users might expect the tab to still be re-opened (e.g. when used as an alarm), but this behavior could be an opt-in once we get a configuration board or something of this kind

**Comment by olliebean** [comment]
Could it at least be prevented from opening several duplicate tabs simultaneously after the computer has been asleep for a several periods?

**Comment by maxlath** [comment]
Following ab6189c and 98900c7a, this is now (`v2.3.3`) the default behavior; the old behavior can be reactivated in the settings.
