### ISSUE TITLE
limit amount of tabs that can be opened at once

### ISSUE THREAD

**Issue by orschiro** [maxlath/time-capsule#9]
Hi @maxlath, 

What a promising extension!

I capsuled two tabs to open every 3 hours. 

How can I now verify that indeed they're on the list of capsuled items (other than waiting 3 hours)?

Where does the extension store these entries?

Is there any way to review them?

Thanks!

**Comment by maxlath** [comment]
yes there is! :D 
open your browser bookmarks menu (Ctrl+Shift+O on Firefox), you should see a folder named `Time Capsules [managed folder]`, all your capsules should be there

**Comment by orschiro** [comment]
Found them, thanks! :-)

Now they just need to trigger...what happens if I switch off or suspend my machine?

Does it continue counting the off time or does it resume counting once I am back online?

![image](https://user-images.githubusercontent.com/170947/48300706-72871f80-e4e2-11e8-93c9-31817019a3e2.png)

**Comment by maxlath** [comment]
every time you open your browser, it will check for capsules that should have been opened in the past and open it right away, which results in tabs hell when coming back from long offline vacations ^^

**Comment by orschiro** [comment]
Oh no! Is that something we can prevent?

That's exactly my fear.

**Comment by maxlath** [comment]
At the moment, no. A work around is to not set too many high frequency capsules, keep an hygiene about it (see [*Advices to keep it sane*](https://maxlath.eu/projects/time-capsule/)). Or accept that when coming back of vacations, you start by closing many tabs, that will be re-opened some time in the future anyway

**Comment by orschiro** [comment]
OK thanks for your advice!

Then, maybe, let's leave this bug open for now until we have found a
better solution?

**Comment by maxlath** [comment]
yes, with an updated title then

**Comment by maxlath** [comment]
but the problem with any strategy trying to limit the amount of tabs being opened at once is that it knowingly breaks the contract that a given URL will be re-opened at some point in time, which might be important (think tax declaration or anything that neeeeeds to be reopened at a somewhat precise moment)

**Comment by caponica** [comment]
So long as you only open *one* of each tab then it's not a big problem. Tab hell will have to be endured as a cost of going on holiday.

**Comment by maxlath** [comment]
Hi from the future! There is now (`v2.3.3`) a setting to limit the amount of tabs that can be opened at once: if more tabs are to be opened, they are instead all listed in a single tab.

PS: I have been playing with setting that value to 0, which gives me great satisfaction: always open in overflow mode => super light on resources ^^
